[package]
name = "axum-msgpack"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"
hyper = "0.14"
mime = "0.3.16"
