[package]
name = "axum-msgpack"
version = "0.2.0"
edition = "2021"

[dependencies]
axum = "0.3"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"
hyper = "0.14"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
tower-service = "0.3"
http = "0.2"
http-body = "0.4.4"
tower = { version = "0.4", features = ["full"] }