[package]
name = "msgpack"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum-msgpack = { path = "../../"}
serde_bytes = "0.11"
axum = "0.3"
serde = { version = "1.0", features = ["derive"] }
